# -*- coding: utf-8 -*-
"""
schemas/recovery.py
===================
Contracts for recovery options, constraint evaluation, and the recovery plan.

Flow:
  ImpactAssessment (impact.py)
      -> DB-enumerated CandidateOption list  <- recovery_agent enumerates from DB
      -> Constraint Engine evaluates each option against C1-C8
      -> ConstraintResult per option
      -> RecoveryPlan                        <- this schema
      -> Human Gate (LangGraph interrupt)
      -> RecoveryPlan.selected_option_id + decided_by + decided_at set post-approval

Architecture rules:
  - CandidateOption is enumerated from DB facts (recovery_option_templates table).
    The LLM formats/labels options but never invents supplier_id, material_id, or costs.
  - ConstraintResult.option_status is distinct from individual rule statuses.
    An option can be APPROVAL_REQUIRED while every rule individually shows PASS
    (C5 is a ROUTE rule, not a HARD fail).
  - RecoveryPlan.selected_option_id, decided_by, decided_at remain None until
    the human gate resolves. The plan is valid in this pre-decision state.
"""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, Field, model_validator


# ─────────────────────────────────────────────────────────────────
# ENUMS
# ─────────────────────────────────────────────────────────────────

class OptionType(str, Enum):
    """
    Locked vocabulary for recovery option categories.
    Matches option_type column in recovery_option_templates table.
    """
    SPOT_BUY   = "SPOT_BUY"    # Purchase from an alternate supplier
    EXPEDITE   = "EXPEDITE"    # Accelerate an existing PO (air freight / partial)
    RESCHEDULE = "RESCHEDULE"  # Push or pull a work order schedule
    SUBSTITUTE = "SUBSTITUTE"  # Use an alternate / substitute material


class RuleStatus(str, Enum):
    """
    Per-rule evaluation result.
    Applied independently per rule per option.
    """
    PASS = "PASS"
    FAIL = "FAIL"   # triggers VETO at option level for HARD rules
    NA   = "NA"     # rule not applicable to this option type


class OptionStatus(str, Enum):
    """
    Option-level status after all rules are evaluated.
    Kept strictly separate from RuleStatus so the UI matrix
    can show APPROVAL_REQUIRED without implying any rule failed.

    PASS              : all HARD rules pass, cost within plant budget
    VETO              : at least one HARD rule failed (C1/C2/C3/C4/C6/C7/C8)
    APPROVAL_REQUIRED : all HARD rules pass, but C5 (ROUTE) threshold exceeded
    """
    PASS               = "PASS"
    VETO               = "VETO"
    APPROVAL_REQUIRED  = "APPROVAL_REQUIRED"


class ApprovalDecision(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING  = "PENDING"


# ─────────────────────────────────────────────────────────────────
# SUB-MODELS
# ─────────────────────────────────────────────────────────────────

class RuleEvaluation(BaseModel):
    """
    Result of evaluating a single rule (e.g. C1) against one option.

    Stored inside ConstraintResult.rules[].
    UI renders this as a checklist row per option.
    """
    rule_id    : str        = Field(..., description="Rule ID from rulebook (e.g. 'C1').")
    rule_name  : str        = Field(..., description="Human-readable rule name.")
    status     : RuleStatus = Field(..., description="PASS / FAIL / NA for this option.")
    evidence   : str        = Field(
        ...,
        description="One-sentence explanation of the verdict. "
                    "Sourced from DB facts -- not generated by LLM. "
                    "Example: 'lead_time_days=18 exceeds available_days=15'."
    )
    threshold  : Optional[str] = Field(
        None,
        description="Rule threshold value from rulebook for reference display."
    )
    actual     : Optional[str] = Field(
        None,
        description="Actual value from supplier/material DB for this option. "
                    "Enables direct comparison in UI: threshold vs actual."
    )


class ConstraintResult(BaseModel):
    """
    Full constraint evaluation for one CandidateOption.

    option_status is the aggregate verdict.
    rules[] is the per-rule breakdown.

    UI contract:
      - option_status drives the row badge (PASS / VETO / APPROVAL_REQUIRED).
      - rules[] drives the expandable checklist per option row.
      - Vetoed options must remain visible in the UI with their evidence.
    """
    option_id    : str          = Field(..., description="Links to CandidateOption.option_id.")
    option_status: OptionStatus = Field(
        ...,
        description="Aggregate option verdict. Separate from individual rule statuses. "
                    "APPROVAL_REQUIRED means all HARD rules passed but C5 ROUTE fired."
    )
    rules        : List[RuleEvaluation] = Field(
        ...,
        min_length=1,
        description="Ordered list of all evaluated rules for this option. "
                    "Must include every applicable rule from the rulebook."
    )
    veto_rules   : List[str] = Field(
        default_factory=list,
        description="rule_ids of rules that caused FAIL (populated when option_status=VETO). "
                    "Empty when status=PASS or APPROVAL_REQUIRED."
    )

    @model_validator(mode="after")
    def veto_requires_failed_hard_rule(self) -> "ConstraintResult":
        """VETO status must have at least one FAIL rule; PASS/APPROVAL_REQUIRED must have none."""
        failed = [r.rule_id for r in self.rules if r.status == RuleStatus.FAIL]
        if self.option_status == OptionStatus.VETO and not failed:
            raise ValueError(
                "option_status=VETO requires at least one RuleEvaluation with status=FAIL."
            )
        if self.option_status == OptionStatus.PASS and failed:
            raise ValueError(
                f"option_status=PASS but rules {failed} have status=FAIL."
            )
        if self.option_status == OptionStatus.APPROVAL_REQUIRED and failed:
            raise ValueError(
                f"option_status=APPROVAL_REQUIRED but rules {failed} have status=FAIL. "
                "APPROVAL_REQUIRED means all HARD rules passed."
            )
        return self

    @model_validator(mode="after")
    def veto_rules_matches_failed(self) -> "ConstraintResult":
        """veto_rules list must match the rule_ids that show FAIL."""
        failed_ids = {r.rule_id for r in self.rules if r.status == RuleStatus.FAIL}
        veto_set   = set(self.veto_rules)
        if failed_ids != veto_set:
            raise ValueError(
                f"veto_rules={sorted(veto_set)} does not match "
                f"failed rule_ids={sorted(failed_ids)}."
            )
        return self


class CandidateOption(BaseModel):
    """
    A single recovery option enumerated from the DB.
    Populated from recovery_option_templates + supplier/material facts.
    LLM provides a formatted label and summary; all numeric fields come from DB.
    """
    option_id    : str        = Field(..., description="Template ID (e.g. 'OPT-A').")
    option_type  : OptionType = Field(..., description="SPOT_BUY / EXPEDITE / RESCHEDULE / SUBSTITUTE.")
    supplier_id  : Optional[str] = Field(None, description="Supplier ID from DB (None for RESCHEDULE).")
    material_id  : Optional[str] = Field(None, description="Material ID from DB (None for RESCHEDULE).")
    description  : str        = Field(..., description="Short description from DB template.")
    total_cost   : float      = Field(
        ...,
        ge=0.0,
        description="Total cost of this option (USD). Read from supplier freight rates in DB. "
                    "Never invented by LLM."
    )
    estimated_arrival: Optional[date] = Field(
        None,
        description="Projected arrival date if option is executed today. "
                    "Computed: reference_date + supplier.lead_time_days."
    )
    days_of_coverage : int = Field(
        ...,
        ge=0,
        description="How many shortage days this option eliminates. "
                    "0 for RESCHEDULE (doesn't bring material). "
                    "Computed deterministically."
    )
    constraint_result: Optional[ConstraintResult] = Field(
        None,
        description="Set after constraint engine evaluates this option. "
                    "None before evaluation."
    )
    llm_summary  : Optional[str] = Field(
        None,
        description="Optional LLM-generated one-sentence summary for UI display. "
                    "Must not contain any numeric values not present in other fields."
    )


# ─────────────────────────────────────────────────────────────────
# MAIN MODEL
# ─────────────────────────────────────────────────────────────────

class RecoveryPlan(BaseModel):
    """
    Complete recovery plan covering all candidate options and the human gate outcome.

    Pre-approval state  : selected_option_id, decided_by, decided_at are None.
    Post-approval state : all three are set after Human Gate resolves.

    The audit summary LLM generates narrative from the structured fields here --
    it never produces numbers; it only narrates what this model contains.
    """

    # ── Context ───────────────────────────────────────────────────
    shipment_id        : str  = Field(..., description="Disrupted shipment driving this plan.")
    po_id              : str  = Field(..., description="Linked purchase order ID.")
    reference_date     : date = Field(..., description="Scenario anchor date.")
    shortage_days      : int  = Field(..., ge=0, description="Net shortage window in days.")
    total_otif_exposure: float= Field(..., ge=0.0, description="Total OTIF exposure (USD).")

    # ── Candidates ────────────────────────────────────────────────
    candidates         : List[CandidateOption] = Field(
        ...,
        min_length=1,
        description="All options enumerated from DB. Includes vetoed options -- "
                    "these must remain visible in the UI with their evidence."
    )

    # ── Constraint summary ────────────────────────────────────────
    vetoed_options     : List[str] = Field(
        default_factory=list,
        description="option_ids with option_status=VETO."
    )
    feasible_options   : List[str] = Field(
        default_factory=list,
        description="option_ids with option_status=PASS or APPROVAL_REQUIRED."
    )

    # ── Human Gate ────────────────────────────────────────────────
    selected_option_id : Optional[str] = Field(
        None,
        description="option_id approved by the human gate. "
                    "None until Human Gate resolves (pre-decision state is valid)."
    )
    approval_decision  : Optional[ApprovalDecision] = Field(
        None,
        description="APPROVED / REJECTED / PENDING. None before gate fires."
    )
    decided_by         : Optional[str] = Field(
        None,
        description="Name or role of the approver (e.g. 'VP Supply Chain'). "
                    "Set post-approval."
    )
    decided_at         : Optional[datetime] = Field(
        None,
        description="Timestamp of approval/rejection decision. Set post-approval."
    )
    rejection_reason   : Optional[str] = Field(
        None,
        description="Reason provided when approval_decision=REJECTED."
    )

    # ── Audit ─────────────────────────────────────────────────────
    audit_summary      : Optional[str] = Field(
        None,
        description="LLM-generated narrative of the full plan, constraints, and decision. "
                    "Populated after Human Gate. Numbers sourced from this model, "
                    "not generated by LLM."
    )

    @model_validator(mode="after")
    def approved_requires_selection(self) -> "RecoveryPlan":
        """APPROVED decision requires selected_option_id and decided_by/decided_at."""
        if self.approval_decision == ApprovalDecision.APPROVED:
            if not self.selected_option_id:
                raise ValueError("approval_decision=APPROVED requires selected_option_id.")
            if not self.decided_by:
                raise ValueError("approval_decision=APPROVED requires decided_by.")
            if not self.decided_at:
                raise ValueError("approval_decision=APPROVED requires decided_at.")
        return self

    @model_validator(mode="after")
    def rejected_requires_reason(self) -> "RecoveryPlan":
        """REJECTED decision should carry a reason."""
        if self.approval_decision == ApprovalDecision.REJECTED and not self.rejection_reason:
            raise ValueError("approval_decision=REJECTED requires rejection_reason.")
        return self

    @model_validator(mode="after")
    def selected_must_be_feasible(self) -> "RecoveryPlan":
        """selected_option_id must come from feasible_options, not vetoed ones."""
        if self.selected_option_id and self.vetoed_options:
            if self.selected_option_id in self.vetoed_options:
                raise ValueError(
                    f"selected_option_id='{self.selected_option_id}' is in vetoed_options. "
                    "Cannot approve a vetoed option."
                )
        return self

    class Config:
        use_enum_values = False
